### ISSUE TITLE
New Package: @dcx-protocol/verifier

### ISSUE THREAD

**Issue by bnonni** [TBD54566975/incubation-dcx#99]
### Summary
- DIF defines the actors in PEX as: Holder and Verifier https://identity.foundation/presentation-exchange/
- DCX is a direct implementation of the DIF PEX specification
- Verifier is more descriptive of how DCX acts within an implemented identity system
- To better align with DIF's PEX spec and to avoid future confusion, we need to implement `@dcx-protocol/verifier`
- Much of the code within the current issuer package would be ported over to the new verifier

![image](https://github.com/user-attachments/assets/3b5cbb4a-cee8-4d5b-935f-6a8f03febf4d)

### Considerations
- Running a DCX server is equivalent to running a verifier
- However, a DCX server could also be the issuer of a credential as well
- Consider what it looks like to have both a verifier and an issuer package
- `verifier` could house the essential software pieces for doing the following:
  - defining credential manifests within presentation definitions
  - ingesting credential applications within presentation submissions
  - verifying signatures of input VCs and making requests to 3rd party issuers or using an `issuer` package to issue VCs
- defining `verifier` and separating it from `issuer` provides a cleaner level of abstraction and design
- users could deploy separate `verifier` and `issuer` servers that interact via API calls
- users could also deploy one server using both the `verifier` and `issuer` packages if desired

### TODO
- [ ] create `@dcx-protocol/verifier`
- [ ] define the requirements for each package
- [ ] review `@dcx-protocol/issuer` and determine which parts of its code are meant to be part of verifier
- [ ] move those parts to the new `verifier` package
- [ ] re-design and implement the `issuer` package
